version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 1

  - package-ecosystem: "npm"
    directory: "/apps/app-gui"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 1

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
