name: Renovate

on:
  schedule:
    - cron: "22 4 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.2.2
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
